sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 4 # LTS
  - stable
before_script:
  - npm prune
after_success:
  - npm run test:coverage && npm run test:coverage:upload
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
